export enum ipcEvents {
    LOGIN = 'lwt-login',
    LOGIN_FAILED = 'lwt-login-failed',
    SIGNUP = 'lwt-signup',
    USER_ID = 'lwt-user-id',
    LANGUAGES = 'lwt-languages',
    ADD_LANGUAGE = 'lwt-add-language',
    GET_LANGUAGE = 'lwt-get-language',
    EDIT_LANGUAGE = 'lwt-edit-language',
    DELETE_LANGUAGE = 'lwt-delete-language',
    ADD_TEXT = 'lwt-add-text',
    GET_TEXT = 'lwt-get-text',
    GET_TEXT_PARSED = 'lwt-get-text-parsed',
    GET_TEXTS = 'lwt-get-texts',
    OPEN_TEXT = 'lwt-open-text',
}
